server:
  context-path: /sell
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://123.56.84.228:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

  jackson:
    default-property-inclusion: non_null

  redis:
    host: 123.56.84.228
    port: 6379


wechat:
  mpAppId: wxb608c570d8bbfe93  //正式个人
  mpAppSecret: d407dfad2d7d5c0fdf95e822f019f194  //正式个人


  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e

  mchId: 1483469312
  mchKey: c976503d34ca432c601361f969fd8d85
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://sell.natapp4.cc/sell/pay/notify
  templateId:
    orderStatus: c976503d34ca432c601361f969fd8d85

projectUrl:
  wechatMpAutorize: http://localhost:8080
  wechatOpenAutorize: http://localhost:8080
  sell:



logging:
  pattern:
    console: "%d - %msg%n"
  path: /var/log/tomcat/
  file: /var/log/tomcat/sell.log
  level:
    com.imooc.LoggerTest: debug