server:
  context-path: /sell
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://123.56.84.228/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

  jackson:
    default-property-inclusion: non_null

wechat:
  mpAppId: wxd898fcb01713c658
  mpAppSecret: 29d8a650db31472aa87800e3b0d739f2


